// vibe-code-starters/angular/src/app.component.ts
import { Component } from "@angular/core";
import { CommonModule } from "@angular/common";

@Component({
  selector: "app-root",
  standalone: true,
  imports: [CommonModule],
  template: `
    <div style="padding: 20px; font-family: sans-serif;">
      <h1>Hello Angular!</h1>
      <p>Start building your app.</p>
    </div>
  `,
  styles: [],
})
export class AppComponent {
  title = "angular-playground";
}

// vibe-code-starters/vue/src/App.vue
<template>
  <div class="hello">
    <h1>Hello Vue!</h1>
    <p>{{ message }}</p>
  </div>
</template>

<script>
export default {
  data() {
    return {
      message: "Welcome to your Vue.js playground!",
    };
  },
};
</script>

<style>
.hello {
  font-family: sans-serif;
  padding: 20px;
}
</style>
